version: "1.0"

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    env_file:
      - ".env"
    logging:
      options:
        max-size: "10m"
    command: [ "postgres", "-c", "log_statement=all", "-p", "${POSTGRES_PORT}"]
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: "."
    env_file:
      - ".compose.env"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
